pub mod engine;
pub mod frame;
pub mod opcode;
pub mod stack;
pub mod assign_op;
pub mod inc_dec;
mod array_access;
mod error_formatting;
mod error_construction;
mod stack_helpers;
mod type_conversion;
mod class_resolution;
mod variable_ops;
mod opcodes;
mod opcode_executor;
